<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <RootNamespace>CNC.Core</RootNamespace>
    <AssemblyName>CNC.Core</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UICulture>en-US</UICulture>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>TRACE;DEBUG;RESPONSELOG;USEWEBSOCKET</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug' AND '$(TargetFramework)' == 'net8.0-windows'">
    <DefineConstants>TRACE;DEBUG;RESPONSELOG;USEWEBSOCKET;WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE;USEWEBSOCKET</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release' AND '$(TargetFramework)' == 'net8.0-windows'">
    <DefineConstants>TRACE;USEWEBSOCKET;WINDOWS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="System.Management" Version="8.0.0" />
    <Page Include="LibStrings.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>